advent_hunt/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = (
    [
        path("", include("huntsite.urls")),
        path("accounts/", include("allauth.urls")),
        path("admin/", admin.site.urls),
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = (
    [
        path("", include("huntsite.urls")),
        path("admin/", admin.site.urls),
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

huntsite/puzzles/forms.py
from crispy_bulma.layout import HTML, FormGroup, Submit
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Field, Layout
from django import forms


class GuessForm(forms.Form):
    guess = forms.CharField(
        label="",
        help_text="",
        max_length=128,
        widget=forms.TextInput(attrs={"class": "input"}),
    )

    def __init__(self, *args, slug: str, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = "guess-form"
        self.helper.attrs = {
            "hx-post": ".",
            "hx-target": "#guesses-results",
            "hx-on::after-request": "if(event.detail.successful) this.reset()",
        }
        self.helper.layout = Layout(
            FormGroup(
                Field("guess"),
                Submit("submit", "Submit", css_class="is-primary"),
                HTML(
                    '<div class="pseudorelative-outer">'
                    '<p class="htmx-indicator pseudorelative-inner loading-indicator is-size-4">'
                    "❄"
                    "</p>"
                    "</div>"
                ),
                css_class="is-align-items-center",
            )
        )

templates/partials/announcement_message.html
{% if ANNOUNCEMENT_MESSAGE %}
  <div class="notification announcement_message">{{ ANNOUNCEMENT_MESSAGE|safe }}</div>
{% endif %}

templates/partials/card_toggle_indicator.html
<button class="card-header-icon card-toggle"
        aria-label="toggle answer checker">
  {% if start_hidden %}
    <span class="icon toggle-open is-hidden"><i class="bi bi-caret-down-fill"></i></span>
    <span class="icon toggle-closed"><i class="bi bi-caret-left-fill"></i></span>
  {% else %}
    <span class="icon toggle-open"><i class="bi bi-caret-down-fill"></i></span>
    <span class="icon toggle-closed is-hidden"><i class="bi bi-caret-left-fill"></i></span>
  {% endif %}
</button>

templates/partials/card_toggle_script.html
<script>
  // Toggles card-content based on click by card header
  document.addEventListener('DOMContentLoaded', function() {
    let toggleables = document.getElementsByClassName('is-toggleable');
    for (let i = 0; i < toggleables.length; i++) {
      let header = toggleables[i].querySelector(".card-header");
      header.classList.add('is-clickable');
      header.addEventListener('click', e => {
        e.currentTarget.parentElement.querySelector(".card-content").classList.toggle('is-hidden');
        e.currentTarget.parentElement.querySelector(".toggle-closed").classList.toggle('is-hidden');
        e.currentTarget.parentElement.querySelector(".toggle-open").classList.toggle('is-hidden');
      });
    }
  });
</script>

templates/partials/clientside_answer_checker.html
<!--CLIENTSIDE ANSWER CHECKER-->
<div id="guess-form-container" class="block">
  <form id="guess-form">
    <div class="field is-grouped is-align-items-center">
      <div class="control">
        <input type="text"
               name="guess"
               class="input"
               maxlength="128"
               required=""
               id="id_guess">
      </div>
      <div class="control">
        <input type="submit"
               name="submit"
               value="Submit"
               class="button is-primary"
               id="submit-id-submit">
      </div>
    </div>
  </form>
</div>
<div id="guesses-results" class="block is-hidden">
  <p id="evaluation-message" class="block"></p>
  <p class="has-text-grey is-size-7 block">
    <i class="bi bi-info-circle"></i> Your guess history is not saved and will be lost if you reload or navigate away.
  </p>
  {% load static %}
  <link href="{% static 'css/liberationmono.css' %}" rel="stylesheet" />
  <table id="guess-list-table" class="guess-list-table table">
    <thead>
      <tr>
        <th scope="col" align="left">Guess</th>
        <th scope="col" align="center">Evaluation</th>
        <th scope="col" align="center">Time</th>
      </tr>
    </thead>
    {# djlint:off H020 #}
    <tbody>
    </tbody>
    {# djlint:on #}
  </table>
</div>
<script>
  evaluations = {
    CORRECT: "correct",
    KEEP_GOING: "keep_going",
    INCORRECT: "incorrect"
  }
  evaluation_messages = {
    [evaluations.CORRECT]: "Correct! 🎉",
    [evaluations.INCORRECT]: "Incorrect.",
    [evaluations.KEEP_GOING]: "You got an intermediate phrase! Keep going for the final answer."
  }
  evaluation_displays = {
    [evaluations.CORRECT]: "Correct",
    [evaluations.INCORRECT]: "Incorrect",
    [evaluations.KEEP_GOING]: "Keep going!"
  }
  const answerData = {{ answer_data|safe }};
  function cleanAnswer(input) {
    return input
    .normalize('NFKD') // Normalize to NFKD
    .toUpperCase() // Convert to uppercase
    .trim() // Remove leading/trailing whitespace
    .replace(/\s+/g, ' ') // Replace internal whitespace with single space
    .replace(/[^A-Z ]/g, ''); // Remove non-alphabetic characters
  }
  function normalizeAnswer(input) {
    return cleanAnswer(input).replace(/\s+/g, '');
  }
  function checkAnswer(guess) {
    const normalizedGuess = normalizeAnswer(guess);
    const normalizedAnswer = normalizeAnswer(atob(answerData.answer));
    const normalizedKeepGoings = answerData.keep_goings.map(atob).map(normalizeAnswer);
    if (normalizedGuess === normalizedAnswer) {
      return evaluations.CORRECT
    } else if (normalizedKeepGoings.includes(normalizedGuess)) {
      return evaluations.KEEP_GOING
    } else {
      return evaluations.INCORRECT
    }
  }
  document.getElementById("guess-form").addEventListener("submit", function (event) {
    event.preventDefault(); // Prevent the default form submission
    const form = event.target;
    const formData = new FormData(form);
    const guess_text = formData.get("guess");
    const evaluation = checkAnswer(guess_text);
    // Unhide evaluation and guess list
    document.getElementById("guesses-results").classList.remove("is-hidden");
    // Update evaluation message
    document.getElementById("evaluation-message").textContent = evaluation_messages[evaluation];
    // Add row to guesses table
    const newRow = document.getElementById("guess-list-table").tBodies[0].insertRow(0);
    newRow.classList.add("guess-list-row");
    const guessCell = newRow.insertCell();
    const guessSpan = document.createElement("span");
    guessSpan.textContent = cleanAnswer(guess_text);
    guessSpan.classList.add("mono");
    guessCell.appendChild(guessSpan);
    guessCell.setAttribute("scope", "col");
    guessCell.setAttribute("align", "left");
    const evaluationCell = newRow.insertCell();
    evaluationCell.textContent = evaluation_displays[evaluation];
    evaluationCell.setAttribute("scope", "col");
    evaluationCell.setAttribute("align", "center");
    const timeCell = newRow.insertCell();
    timeCell.textContent = moment.tz(Date.now(), userTimeZone).format('MMM D, YYYY hh:mm:ss A z');
    evaluationCell.setAttribute("scope", "col");
    evaluationCell.setAttribute("align", "center");
    this.reset();
  })
</script>

templates/partials/form.html
{% comment %} Partial for generic form that can be replaced with htmx {% endcomment %}
{% load crispy_forms_tags %}
{% crispy form %}

templates/partials/messages.html
{% load common_extras %}
{% if messages %}
  {% for message in messages %}
    <div class="notification {% if message.tags %} {% with message.tags|split as tags %} {% for tag in tags %}is-{{ tag }}{% endfor %} {% endwith %} {% endif %}">
      <button class="delete"></button>
      {{ message }}
    </div>
  {% endfor %}
  <script>
    document.addEventListener('DOMContentLoaded', () => {
      (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
        const $notification = $delete.parentNode;

        $delete.addEventListener('click', () => {
          $notification.parentNode.removeChild($notification);
        });
      });
    });
  </script>
{% endif %}

templates/partials/navbar.html
{% load static %}
<nav class="navbar is-info" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <a class="navbar-item merienda" href="{% url 'home' %}">
        {% if hunt_state == HuntState.PREHUNT or user.is_finished %}
          {% comment %} Normal Santa Logo {% endcomment %}
          <picture>
            <source srcset="{% static 'santa/icon.svg' %}"
                    width="56"
                    height="56"
                    type="image/svg+xml">
            <img src="{% static 'santa/icon-56.png' %}"
                 width="56"
                 height="56"
                 alt="Santa" />
          </picture>
        {% else %}
          {% comment %} Santa Missing Logo {% endcomment %}
          <picture>
            <source srcset="{% static 'santa-missing-dark/icon.svg' %}"
                    width="56"
                    height="56"
                    type="image/svg+xml">
            <img src="{% static 'santa-missing-dark/icon-56.png' %}"
                 width="56"
                 height="56"
                 alt="Silhouette of Santa with a question mark" />
          </picture>
        {% endif %}
        Advent Hunt
      </a>
      <a role="button"
         class="navbar-burger"
         data-target="navMenu"
         aria-label="menu"
         aria-expanded="false">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
    <div class="navbar-menu" id="navMenu">
      <div class="navbar-start">
        <a class="navbar-item" href="{% url 'home' %}">Home</a>
        <a class="navbar-item" href="{% url 'puzzle_list' %}">Puzzles</a>
        <a class="navbar-item" href="{% url 'story' %}">Story</a>
        <a class="navbar-item" href="{% url 'team_list' %}">Teams</a>
        <a class="navbar-item" href="{% url 'about' %}">About</a>
        <a class="navbar-item" href="{% url 'updates' %}">Updates</a>
        {% if wrapup_is_available %}
          <a class="navbar-item" href="{% url 'wrapup' %}">Wrap-up</a>
        {% endif %}
        {% if DISCORD_SERVER_LINK and user.is_authenticated and hunt_state < HuntState.ENDED %}
          <a class="navbar-item"
             id="discord-server-link"
             style="column-gap: 0.5rem"
             href="{{ DISCORD_SERVER_LINK }}"><i class="bi bi-discord"></i>Discord</a>
        {% endif %}
      </div>
      {% if hunt_state < HuntState.ENDED %}
        <div class="navbar-end">
          {% if user.is_authenticated %}
            <a class="navbar-item" href="{% url 'team_detail' user.id %}">{{ user.team_name|truncatechars:36 }}</a>
            <a class="navbar-item"
               href="#"
               onClick="document.getElementById('logout-form').submit()">Logout</a>
          {% else %}
            <a class="navbar-item" href="{% url 'account_login' %}">Login</a>
            <a class="navbar-item" href="{% url 'account_signup' %}">Register</a>
          {% endif %}
        </div>
      {% endif %}
    </div>
  </div>
</nav>

templates/partials/puzzle_calendar_cell_available.html
<div id="calendar-cell-{{ day }}"
     class="cell has-text-centered puzzle-calendar-cell">
  <div class="box {% if puzzle.is_solved %}solved{% else %}available{% endif %} {% if puzzle.meta_info %}meta{% endif %}">
    <p class="day block">{{ puzzle.calendar_entry.day }}</p>
    <p class="puzzle-name block">
      <a href="{{ puzzle.get_absolute_url }}" rel="nofollow">{{ puzzle.title }}
        {% if not puzzle.is_available %}<span class="tag is-danger">Preview</span>{% endif %}
      </a>
    </p>
    <p class="puzzle-answer block">
      {% if puzzle.is_solved %}<strong><span class="mono">{{ puzzle.answer }}</span></strong>{% endif %}
    </p>
    {% if puzzle.meta_info %}<div class="meta-icon">{{ puzzle.meta_info.icon|safe }}</div>{% endif %}
  </div>
</div>

templates/partials/puzzle_calendar_cell_unavailable.html
<div id="calendar-cell-{{ day }}"
     class="cell puzzle-calendar-cell has-text-centered">
  <div class="box unavailable is-flex is-justify-content-center is-align-items-center">
    <span class="unavailable-day">{{ day }}</span>
  </div>
</div>

templates/partials/puzzle_guess_list.html
{% if evaluation_message %}
  <p id="evaluation-message" class="block">{{ evaluation_message }}</p>
  {% if story_unlock_message %}<p class="block">{{ story_unlock_message }}</p>{% endif %}
{% endif %}
{% load static %}
<link href="{% static 'css/liberationmono.css' %}" rel="stylesheet" />
<table class="guess-list-table table">
  <thead>
    <tr>
      <th scope="col" align="left">Guess</th>
      <th scope="col" align="center">Evaluation</th>
      <th scope="col" align="center">Time</th>
    </tr>
  </thead>
  <tbody>
    {% for guess in guesses %}
      <tr class="guess-list-row">
        <td align="left">
          <span class="mono">{{ guess.text }}</span>
        </td>
        <td align="center">{{ guess.display_evaluation }}</td>
        <td align="right" class="nowrap">
          <span class="timestamp">{{ guess.created_at|date:"c" }}</span>
        </td>
      </tr>
    {% endfor %}
  </tbody>
  {% include "partials/timestamp_localize_script.html" %}
</table>

templates/partials/story_prehunt.html
{% load static %}
<link href="{% static 'css/story_prehunt.css' %}" rel="stylesheet" />
<p class="block has-text-centered">You receive an exciting piece of mail from the North Pole. You open it:</p>
<!--...-->
<div class="holiday-card block">
  <div class="holiday-card-outer has-text-centered">
    <p class="merienda is-size-2">Merry Christmas!</p>
    <div class="holiday-card-tree">
      <i class="bi bi-tree-fill"></i>
    </div>
    <div class="holiday-card-gift-1">
      <i class="bi bi-gift-fill"></i>
    </div>
    <div class="holiday-card-gift-2">
      <i class="bi bi-gift-fill"></i>
    </div>
    <div class="holiday-card-star">
      <i class="bi bi-star-fill"></i>
    </div>
    <div class="holiday-card-candy-cane-1">{% include "partials/svgs/candy-cane.svg" %}</div>
    <div class="holiday-card-candy-cane-2">{% include "partials/svgs/candy-cane.svg" %}</div>
    <div class="holiday-card-candy-cane-3">{% include "partials/svgs/candy-cane.svg" %}</div>
    <div class="holiday-card-candy-cane-4">{% include "partials/svgs/candy-cane.svg" %}</div>
  </div>
  <div class="holiday-card-inner-left has-text-centered">
    <div class="holiday-card-santa">
      <img src="{% static 'santa/icon.svg' %}"
           height="192"
           width="192"
           alt="Santa"
           onerror="this.src='{% static 'santa/icon-192.png' %}'" />
    </div>
    <div class="holiday-card-candy-cane-1">{% include "partials/svgs/candy-cane.svg" %}</div>
    <div class="holiday-card-candy-cane-2">{% include "partials/svgs/candy-cane.svg" %}</div>
    <div class="holiday-card-candy-cane-3">{% include "partials/svgs/candy-cane.svg" %}</div>
    <div class="holiday-card-candy-cane-4">{% include "partials/svgs/candy-cane.svg" %}</div>
  </div>
  <div class="holiday-card-inner-right">
    <div class="holiday-card-message content">
      <p>Ho ho ho!</p>
      <p>You're at the top of my Nice List this year. Excellent job!</p>
      <p>
        As a reward for your good behavior, I have a special gift for you: a visit to the North Pole this Christmas season! You will get to see the elves and me in action as we prepare to bring joy to children around the world.
      </p>
      <p>Merry Christmas!</p>
      <p>
        <span class="merienda">Santa Claus</span>
      </p>
    </div>
  </div>
</div>
<!--...-->

templates/partials/tester_controls.html
{% load static %}
{% load crispy_forms_tags %}
{% load common_extras %}
<link href="{% static 'css/tester_controls.css' %}" rel="stylesheet" />
<div class="tester-controls-container">
  <div class="tester-controls-popup-container block">
    {% comment %} Answer Cheatsheet Popup {% endcomment %}
    {% if puzzle %}
      <div id="tester-controls-answer-cheatsheet" class="box">
        <p class="block">
          Answer:
          <br>
          <strong><span class="mono spoiler scheme-background">{{ puzzle.answer }}</span></strong>
        </p>
        {% if puzzle.keep_going_answers %}
          <p class="block">
            Keep Going:
            <br>
            <strong><span class="mono spoiler scheme-background">{{ puzzle.keep_going_answers|join:'</span></strong><br><strong><span class="mono spoiler scheme-background">' }}</span></strong>
          </p>
        {% endif %}
      </div>
    {% endif %}
    {% comment %} Time Travel Popup {% endcomment %}
    <div id="tester-time-travel-form" class="box">{% crispy time_travel_form %}</div>
    {% comment %} --- {% endcomment %}
  </div>
  <div class="tester-controls-buttons-container is-flex is-justify-content-right block">
    {% comment %} Answer Cheatsheet Toggle {% endcomment %}
    {% if puzzle %}
      <button type="button" id="tester-answer-toggle" class="button is-danger">
        <i id="tester-answer-toggle-icon" class="bi bi-dash-lg"></i>&nbsp;
        Reveal Answer
      </button>
    {% endif %}
    {% comment %} Time Travel Toggle {% endcomment %}
    <button type="button"
            id="tester-time-travel-toggle"
            class="button is-danger ml-4">
      <i id="tester-time-travel-toggle-icon" class="bi bi-dash-lg"></i>&nbsp;
      {% if time_traveling_at %}
        Time Traveling at {{ time_traveling_at|date:'Y-m-d H\:i' }} UTC
      {% else %}
        Time Travel
      {% endif %}
    </button>
    {% comment %} --- {% endcomment %}
  </div>
</div>
<script>
  // Time travel toggle
  {
    const button = document.getElementById("tester-time-travel-toggle");
    const toggleIcon = document.getElementById("tester-time-travel-toggle-icon");
    const popup = document.getElementById("tester-time-travel-form");
    popup.style.display = "none";

    button.addEventListener("click", () => {
      if (popup.style.display === "none") {
        popup.style.display = "block";
        toggleIcon.className = "bi bi-chevron-up";
      } else {
        popup.style.display = "none";
        toggleIcon.className = "bi bi-dash-lg";
      }
    });
  }
</script>
{% if puzzle %}
  <script>
    // Answer cheatsheet toggle
    {
      const button = document.getElementById("tester-answer-toggle");
      const toggleIcon = document.getElementById("tester-answer-toggle-icon");
      const popup = document.getElementById("tester-controls-answer-cheatsheet");
      popup.style.display = "none";

      button.addEventListener("click", () => {
        if (popup.style.display === "none") {
          popup.style.display = "block";
          toggleIcon.className = "bi bi-chevron-up";
        } else {
          popup.style.display = "none";
          toggleIcon.className = "bi bi-dash-lg";
        }
      });
    }
  </script>
{% endif %}

templates/partials/timestamp_localize_libraries.html
<script src="https://cdn.jsdelivr.net/npm/moment@2.30.1/moment.min.js"
        integrity="sha384-aQgnUSsW4D+imRFZ/dILN0wXp3MGO6RE3ccC/gZHr6BQzvhwzD+Bzon5C+kO3NHQ"
        crossorigin="anonymous"
        referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.5.45/moment-timezone-with-data-10-year-range.min.js"
        integrity="sha512-v3mDTnfNpDAjWiu1CZZeQrbpI7hKVolNn1Zjc9Spj86hu6jd2HpId4TtJAzbicWZ5ZTAibg72mpG+Zl2F6KQRA=="
        crossorigin="anonymous"
        referrerpolicy="no-referrer"></script>
<script>const userTimeZone = moment.tz.guess();</script>

templates/partials/timestamp_localize_script.html
<script>
    document.querySelectorAll('.{{timestamp_class|default:"timestamp"}}').forEach((element) => {
        const timestamp = element.textContent;
        const localTime = moment.tz(timestamp, userTimeZone).format('{{output_format|default:"MMM D, YYYY hh:mm:ss A z"}}');
        element.textContent = localTime;
    });
</script>